# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, null=True)),
                ('count_1', models.DecimalField(decimal_places=2, max_digits=9)),
                ('count_2', models.DecimalField(decimal_places=2, max_digits=9)),
                ('count_3', models.DecimalField(decimal_places=2, max_digits=9)),
                ('count_theoretical', models.DecimalField(decimal_places=2, max_digits=9)),
                ('count_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventit.CountHeader')),
            ],
        ),
    ]
