# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventit", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="countlines",
            name="count_1",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="countlines",
            name="count_2",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="countlines",
            name="count_3",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="countlines",
            name="item_code",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
