# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-26 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventit', '0005_countheader_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countlines',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='count_lines', to='inventit.Category'),
        ),
    ]
