# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventit', '0007_auto_20190516_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countlines',
            name='item_code',
        ),
    ]
