# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-17 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventit", "0008_remove_countlines_item_code")]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="count_summary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        )
    ]
