# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-18 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventit', '0009_inventory_count_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countlines',
            name='count_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventit.CountHeader'),
        ),
    ]
