# Generated by Django 2.0 on 2021-01-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventit', '0011_auto_20201019_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cost',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
