# Generated by Django 2.0 on 2021-01-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventit', '0012_auto_20210107_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
